import Provider from "@/components/Provider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen antialiased">
        <Provider>
          <main className="h-screen dark text-foreground bg-background">
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
